### PR TITLE
Globally replaced layout-css attribute to layout-style.

### PR DESCRIPTION
**Pull request by bjedrzejewski**
I replaced the attribute everywhere in the sources, site and tests. I did quick manual check on the site that it still works correctly.

### CODE REVIEW

**Comment by chrisprice** [comment]
Looks good to me but as I reported the issue I'd like @colineberhardt to take a quick look.

**Comment by ColinEberhardt** [comment]
Thanks @bjedrzejewski - looks good to me.

Looks like a few other commits have crept into this branch / pull request. Can you remove those so that I can merge?

Thanks :-)

**Comment by bjedrzejewski** [comment]
I have removed the bad commits

**Comment by bjedrzejewski** [comment]
I really messed up this one, so I will reopen once I clean it all up.

**Comment by ColinEberhardt** [comment]
No worries - I'm a bit busy this week, but I'd be happy to help you with
navigating around git next week if you like?

On Thu, Oct 15, 2015 at 12:57 p.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
I really messed up this one, so I will reopen once I clean it all up.

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/619#issuecomment-148365606] .[https://github.com/notifications/beacon/ABDBfgxb2iCiOSAQuT1IHaj5gPqpdkyZks5o74wpgaJpZM4GPRVo.gif]

**Comment by bjedrzejewski** [comment]
Thanks Collin, some advice on how to maintain your github fork would be useful (keeping it in sync with the ScottLogic one) as this is what I am not sure I am doing right.

**Pull request closed without merging**
