### PR TITLE
Rename fc.util.dataJoin().attrs to attr

### PR DESCRIPTION
**Pull request by chrisprice**
In keeping with d3.selection().attr

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
As `attr` supports `(key, value)`, is it worth updating the single-valued usages to this syntax?

**Comment by chrisprice** [comment]
I can definitely do that

**Comment by chrisprice** [comment]
Done :)

**Comment by ColinEberhardt** [comment]
> Done :)

awesome

**Pull request merged**
