### PR TITLE
Added Yahoo Finance to the examples page

### PR DESCRIPTION
**Pull request by ColinEberhardt**
I've added the example as an iframe to the bl.ocks page. 

Long term we need to decide where these examples should live, but this at least gets it added to the site and justifies the plural 'EXAMPLES' menu link ;-)

### CODE REVIEW

**Comment by chrisprice** [comment]
I can taste the bile at the back of my throat! :mask: 

I'll fix it when I stick the basecoin example in.

**Comment by ColinEberhardt** [comment]
At the risk of bringing that bile back up, what by will you be fixing?
(Nice emoticon by the way!)

On Thu, Jul 23, 2015 at 4:52 pm, ScottLogic/d3fc
<reply@reply.github.com>
wrote:
I can taste the bile at the back of my throat!:mask: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f637.png]

I'll fix it when I stick the basecoin example in.

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/501#issuecomment-124149643] .[https://github.com/notifications/beacon/ABDBfgNX_cgs8Ygo_7IKOWm_9TXHuHtqks5ogQVLgaJpZM4FePau.gif]

**Comment by chrisprice** [comment]
(Assuming you meant what will you be fixing) I was going to -

* [ ] make the examples folder match the components folder structure
* [ ] separate out each into it's own page 
* [ ] stick a menu down the side
* [ ] un-gist your example

**Comment by ColinEberhardt** [comment]
Yeah, that's what my mangled question was - thanks for the update :-)

On Thu, Jul 23, 2015 at 5:11 pm, ScottLogic/d3fc
<reply@reply.github.com>
wrote:
(Assuming you meant what will you be fixing) I was going to -

 * make the examples folder match the components folder structure
 * separate out each into it's own page
 * stick a menu down the side
 * un-gist your example

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/501#issuecomment-124154005] .[https://github.com/notifications/beacon/ABDBfl-vzoQwJwM5YUnnMkkgQ77rKXyxks5ogQmngaJpZM4FePau.gif]

**Pull request merged**
