### PR TITLE
WIP: Base series

### PR DESCRIPTION
**Pull request by chrisprice**
Based on our discussions earlier, any thoughts?

It seems to save a significant amount of code and feels quite elegant (even in bar!).

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
I agree, this looks really good - with bar it allows you to clearly see the bar rendering logic without the generic series boiler-plate.

**Comment by ColinEberhardt** [comment]
I agree, this looks really good - with bar it allows you to clearly see the bar rendering logic without the generic series boiler-plate.

**Comment by chrisprice** [comment]
Hm run into a few problems with ohlc/candlestick

**Comment by chrisprice** [comment]
Superseded by #608

**Pull request closed without merging**
