### PR TITLE
Implements absolute padding

### LINKED ISSUE #794: fc.util.extent() supports relative padding, but not absolute padding
Currently `fc.util.extent()` supports padding of data by a percentage, but in order to pad by a fixed amount, the user has to transform this padding into either a percentage, or points to be included in the extent- for which they probably need to run fc.util.extent() beforehand to find the original extent.

The use-case that I am currently trying to implement is the padding of a time domain by half a period in the situation, where calculations to ascertain this are uncertain due to possible missing data points.

Another use-case could be a simple graph displaying variations over time, where an absolute padding could act as a visual representation of the variance of the data. So if the padding was 5, and the range of the data was 10, it would take up 50% of the graph height. If the range of the data was 30, it would take up 75% of the graph height. I imagine that this is functionality that people may desire?

### PR DESCRIPTION
**Pull request by djmiley**
Resolves #794

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Hi @djmiley - sorry it's taken a while to review this. I've had a look at these changes and discussed with @chrisprice also. I'm happy with the concept of adding absolute as well as percentage padding to the API. However, I'm not so keen on the proposed API.

A few issues:

 1. The updated API is pretty verbose, whereas D3 favours quite a terse syntax
 2. The precedence order of absolute / percent padding is not terribly obvious
 3. This is a breaking change, in order to release a [few other updates would be required](https://github.com/ScottLogic/d3fc/search?utf8=%E2%9C%93&q=.pad).

How about as an alternative ... keep the existing `pad` method, but supplement the behavior with a `padUnit` property:

```
fc.util.extent()
      .fields(fields)
      .padUnit('percent')
      .pad(0.5)(data);
```

Where `padUnit` takes values of `percent` or `domain`, with `percent` being the default.

I think this fixes the issues mentioned above.

**Comment by djmiley** [comment]
Thanks for looking at this @ColinEberhardt . That sounds good, I originally thought about implementing this way but wasn't entirely sure which was the best option.

**Comment by ColinEberhardt** [comment]
Thanks for the updates @djmiley - looks good to me :-)

**Comment by ColinEberhardt** [comment]
@djmiley I'll perform a release later today so that you can pick up these changes. I'm just awaiting a few updates on #800 which can hopefully be merged too.

**Comment by ColinEberhardt** [comment]
@djmiley this has been released https://github.com/ScottLogic/d3fc/releases/tag/v5.2.0

**Pull request merged**
