### PR TITLE
Update multi to always order series containers in the same order as specified in the series array

### LINKED ISSUE #537: Should multi series always order elements in the same order as specified in the series array?
It can be confusing that the ordering of the series (specified in an array passed to multi's series method) doesn't always match the order of the series' associated groups in the DOM. Should multi always guarantee this ordering?

Current behaviour:

```js
var mutli = fc.series.multi()
    .series([a, b, c]);

// call multi on selection. output:
// <g><!-- series a --></g>
// <g><!-- series b --></g>
// <g><!-- series c --></g>

multi.series([a, c, b]);

// call multi on selection
// B and C remain in the same order
// output:
// <g><!-- series a --></g>
// <g><!-- series b --></g>
// <g><!-- series c --></g>
```

Suggested change to behaviour:

```js
var mutli = fc.series.multi()
    .series([a, b, c]);

// call multi on selection. output:
// <g><!-- series a --></g>
// <g><!-- series b --></g>
// <g><!-- series c --></g>

multi.series([a, c, b]);

// call multi on selection
// B and C have swapped order - matching the order in the series array
// output:
// <g><!-- series a --></g>
// <g><!-- series c --></g>
// <g><!-- series b --></g>
```

If not, I think this behaviour should be documented.

I'm happy to either update multi and write some tests, and/or update the docs - which ever is preferable.

### PR DESCRIPTION
**Pull request by jleft**
Resolves #537

### CODE REVIEW

**Comment by chrisprice** [comment]
Thanks for the fix. Can't see any problems with the implementation but maybe a custom matcher would simplify the tests?

**Comment by ColinEberhardt** [comment]
Thanks, I like the comprehensive unit tests too.

On Sun, Oct 4, 2015 at 3:47 p.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
Thanks for the fix. Can't see any problems with the implementation but maybe a
custom matcher would simplify the tests?

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/582#issuecomment-145355015] .[https://github.com/notifications/beacon/ABDBfiIiPXfQXBi6Z264UIgC9lFITkbnks5o4TOLgaJpZM4GIlqY.gif]

**Comment by jleft** [comment]
No problem, thanks.

>  Can't see any problems with the implementation but maybe a custom matcher would simplify the tests?

Sure, I'll update with a custom matcher.

**Comment by jleft** [comment]
> Sure, I'll update with a custom matcher.

Done. (Not strictly using a custom matcher, but I think the tests are much simpler than before.)

**Comment by ColinEberhardt** [comment]
Thanks @jleft - this looks really good.

**Pull request merged**
