### PR TITLE
Eslint rules for no-shadow and fixes required. 

### LINKED ISSUE #613: Add eslint rule for our module naming convention
Enforce an import naming convention of -

``` js
// If there are no naming conflicts, just the imported filename
import dataJoin from '../util/dataJoin';
// To avoid potential naming conflicts, the imported filename suffixed by its containing package name
import dataJoinUtil from '../util/dataJoin';
```

E.g. (N.B. the below links no longer resolve to the intended examples) -
https://github.com/ScottLogic/d3fc/pull/600/files#r41894677
https://github.com/ScottLogic/d3fc/pull/600/files#r41894666

### PR DESCRIPTION
**Pull request by bjedrzejewski**
Eslint rule:
"no-shadow": [2, {"builtinGlobals": false, "hoist": "all"}],

...with all the fixes necessary to make it actually build.

### CODE REVIEW

**Comment by bjedrzejewski** [comment]
@chrisprice is this eslint rule what you were looking for? If so I can fix it so it merges, otherwise we can change the rule or close the PR.

**Comment by chrisprice** [comment]
Thanks @bjedrzejewski, these look like valuable changes but #613 was meant to refer to enforcing a naming convention of -

```js
// If there are no naming conflicts, just the imported filename
import dataJoin from '../util/dataJoin';
// To avoid potential naming conflicts, the imported filename suffixed by its containing package name
import dataJoinUtil from '../util/dataJoin';
```

As such I've edited the PR to not close the issue but I'd still like to see this one merged. Are you ok to fix the merge conflicts?

**Comment by chrisprice** [comment]
Just spotted that you've referenced #613 in the commit message as well, please could you rebase that out.

**Comment by bjedrzejewski** [comment]
@chrisprice I merged and rebased off the the close comment.

**Comment by ColinEberhardt** [comment]
@chrisprice are you ok to take a look at this one?

**Comment by chrisprice** [comment]
@bjedrzejewski Thanks, sorry I've only just gotten around to looking at this. There's a change from the property name `root` to `rootValue`. Obviously, if we make this change then we need to release this as a breaking change. Just checking if it was intentional?

**Comment by bjedrzejewski** [comment]
@chrisprice good spot, this was unnecessary! I rebased it out now.

**Comment by chrisprice** [comment]
Great thanks! Looks like we're having intermittent build issues :unamused:

**Comment by bjedrzejewski** [comment]
@chrisprice yeah there is something wrong with the scatterplot example...

**Pull request merged**
