### PR TITLE
Add transition support to ohlc/candlestick

### LINKED ISSUE #740: ohlc/candlestick series don't transition

### PR DESCRIPTION
**Pull request by chrisprice**
Closes #740 and contributes to with #212

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Just wondering, what does 'supporting transitions' look like in the case of ohlc/candlestick? For bars we provide semantic enter transitions by having the bar grow upwards from the y0 line to meet the y1 value while fading in. Update transitions are pretty self explanatory.

**Comment by chrisprice** [comment]
You can see it in the update visual test, in this case I just have the ohlc/candlestick "bars" grow from the middle out.

**Comment by chrisprice** [comment]
I've fixed the merge conflicts

**Comment by ColinEberhardt** [comment]
Thanks - I've got a whole stack of merges to do, then I'll do a release

**Comment by ColinEberhardt** [comment]
Looks good - thanks Chris.

**Pull request merged**
