### PR TITLE
Move fields to be a property on extent

### PR DESCRIPTION
**Pull request by owennw**

### CODE REVIEW

**Comment by jdunkerley** [comment]
Looks good to me.

**Comment by ColinEberhardt** [comment]
This is looking really good - thanks @owennw 

I just spotted a couple of places where we could make better use of these new features:

https://github.com/ColinEberhardt/d3-financial-components/commit/d642155bcde0b1c8c734a16bf98ca29eb80a7a76

Once these build passes,I'll merge.

**Comment by owennw** [comment]
I did see those two places and thought about doing the tweaks, but wanted to keep the commit simple. D'oh.

**Comment by ColinEberhardt** [comment]
No problem, this was a very useful set of changes

On Wed, Oct 28, 2015 at 4:53 p.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
I did see those two places and thought about doing the tweaks, but wanted to
keep the commit simple. D'oh.

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/694#issuecomment-151907957] .[https://github.com/notifications/beacon/ABDBfk08wGiudv6uX_dMUsc36dxkjdFDks5pAPUbgaJpZM4GXXo6.gif]

**Pull request merged**
