### PR TITLE
Allow extent to support symmetrical domains #728

### PR DESCRIPTION
**Pull request by owennw**

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Looks great :-)

My only request, before merging, is that you roll this new feature out across the website examples. I think it would be useful for MACD, Elder and Force Index - perhaps others.

Thanks :-)

**Comment by owennw** [comment]
Done, raised #734 to deal with the extent for Elder Ray. Took a look at the others and didn't see any candidates.

**Comment by ColinEberhardt** [comment]
As I mentioned in #732, I think I'd prefer to see the component construction separated from the invocation. I think this is easier for people who are new to d3 / d3fc to understand. In this case that would mean the following pattern:

```
var yDomain = fc.util.extent
     .fields(function(d) { return Math.abs(d.macd.macd); })
     .symmetricAbout(0);

foo.domain(yDomain(data))
```

**Comment by owennw** [comment]
I've pushed what I meant to now..

**Comment by ColinEberhardt** [comment]
Nice job :+1:

**Pull request merged**
