### PR TITLE
Small multiples - ready for initial review

### LINKED ISSUE #519: Add small multiples component
Suggestion from @godds, add a small multiples component -

http://www.juiceanalytics.com/writing/better-know-visualization-small-multiples

http://blog.scottlogic.com/2011/09/23/a-critique-of-radar-charts.html (scroll down to Alternatives)

Potential features of component -

* Layout
* Axes only on border charts

### PR DESCRIPTION
**Pull request by ColinEberhardt**
fixes #519

Small multiples, makes pretty charts :-)

screen shot 2015-10-22 at 21 36 28

The small multiples component is actually quite similar to cartesian chart, it shares similar axis orientation logic, margins etc ...

The code is at a point where it would be good to get a bit of feedback. Here is my current TODO list:

 - [x] Try out using flexbox layout for rendering the multiples - this might give a more flexible label placement, **conclusion:** this was too complex, requiring nested elements (i.e. column containers), with a nested datajoin for the layout and nasty logic to determine which series to plot in each multiple container
 - [x] Modify stack / grouped series types. Currently these expect an array of arrays, where the nested arrays have a `key` property. Small multiples is more flexible, having `key` and `values` accessors. This is much more compatible with the way `d3.nest` works.
 - [x] The logic [here](https://github.com/ColinEberhardt/d3-financial-components/blob/small-multiples/visual-tests/chart/small-multiples.js#L118) is similar to our `spread` component, however rather than create a series for each column, it creates a series from each row. Perhaps `spread` should have an `orient` property and include this logic?
 - [x] Add small multiples to website and update stack / group (if required)
 - [x] Check the website for breaking changes!

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
On another note, does the way the domain line within the axis renders end 'caps' bother anyone else?

screen shot 2015-10-22 at 21 46 05

**Comment by ColinEberhardt** [comment]
I've updated stacked / grouped to use accommodate the same data format. One side effect is that the extent function is now more complex:

```
var yDomain = fc.util.extent(series.map(function(d) { return d.values; }), function(d) { return 0; }, 'y');
```

The extent function accommodates arrays of arrays, but not arrays where the nested array is within an object property (in this case `values`. Perhaps extent and spread could collaborate somehow?

I've also standardised the CSS for charts, where each chart has the `chart` class and a more specific class, e.g. `chart multiples`, `chart cartesian`

**Comment by chrisprice** [comment]
Not had a chance to look over the rest but this definitely annoys me. Feels
like there should be a d3 issue...

**Comment by chrisprice** [comment]
http://stackoverflow.com/questions/13669239/remove-end-ticks-from-d3-js-axis

**Comment by ColinEberhardt** [comment]
We have our own svg axis implementation, so could fix this one quite simply ...
axis.endCaps(false)


On Fri, Oct 23, 2015 at 8:07 a.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
http://stackoverflow.com/questions/13669239/remove-end-ticks-from-d3-js-axis
[http://stackoverflow.com/questions/13669239/remove-end-ticks-from-d3-js-axis]

On Fri, 23 Oct 2015 08:06 Chris Price <price.c@gmail.com> wrote:

> Not had a chance to look over the rest but this definitely annoys me.
> Feels like there should be a d3 issue...
>
> On Thu, 22 Oct 2015 21:47 Colin Eberhardt <notifications@github.com>
> wrote:
>
>> On another note, does the way the domain line within the axis renders end
>> 'caps' bother anyone else?
>>
>> [image: screen shot 2015-10-22 at 21 46 05]
>> < 
https://cloud.githubusercontent.com/assets/1098110/10677799/6c506bb2-7906-11e5-9e44-beee9aa67054.png
[https://cloud.githubusercontent.com/assets/1098110/10677799/6c506bb2-7906-11e5-9e44-beee9aa67054.png] >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> < https://github.com/ScottLogic/d3fc/pull/664#issuecomment-150351570
[https://github.com/ScottLogic/d3fc/pull/664#issuecomment-150351570] >.
>>
>
—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/664#issuecomment-150494017] .[https://github.com/notifications/beacon/ABDBfjX18YcrtU1eMq50SPlOcCrDPhxEks5o-dRGgaJpZM4GUFPv.gif]

**Comment by ColinEberhardt** [comment]
Ah, just looked at the implementation, it is already possible via outerTickSize.
I think it is just a problem of poor naming and choice of defaults.

On Fri, Oct 23, 2015 at 8:11 a.m., colin.eberhardt@gmail.com
<colin.eberhardt@gmail.com> wrote:
We have our own svg axis implementation, so could fix this one quite simply ...
axis.endCaps(false)


On Fri, Oct 23, 2015 at 8:07 a.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
[http://stackoverflow.com/questions/13669239/remove-end-ticks-from-d3-js-axis] http://stackoverflow.com/questions/13669239/remove-end-ticks-from-d3-js-axis
[http://stackoverflow.com/questions/13669239/remove-end-ticks-from-d3-js-axis]

On Fri, 23 Oct 2015 08:06 Chris Price <price.c@gmail.com> wrote:

> Not had a chance to look over the rest but this definitely annoys me.
> Feels like there should be a d3 issue...
>
> On Thu, 22 Oct 2015 21:47 Colin Eberhardt <notifications@github.com>
> wrote:
>
>> On another note, does the way the domain line within the axis renders end
>> 'caps' bother anyone else?
>>
>> [image: screen shot 2015-10-22 at 21 46 05]
>> < 
[https://cloud.githubusercontent.com/assets/1098110/10677799/6c506bb2-7906-11e5-9e44-beee9aa67054.png] 
https://cloud.githubusercontent.com/assets/1098110/10677799/6c506bb2-7906-11e5-9e44-beee9aa67054.png
[https://cloud.githubusercontent.com/assets/1098110/10677799/6c506bb2-7906-11e5-9e44-beee9aa67054.png] >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> < [https://github.com/ScottLogic/d3fc/pull/664#issuecomment-150351570] https://github.com/ScottLogic/d3fc/pull/664#issuecomment-150351570
[https://github.com/ScottLogic/d3fc/pull/664#issuecomment-150351570] >.
>>
>
—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/664#issuecomment-150494017] .[https://github.com/notifications/beacon/ABDBfjX18YcrtU1eMq50SPlOcCrDPhxEks5o-dRGgaJpZM4GUFPv.gif]

**Comment by chrisprice** [comment]
Looks good, a few comments from creating [my own example](https://github.com/ColinEberhardt/d3-financial-components/compare/small-multiples...chrisprice:small-multiples) -

* The default settings render an axis on the left but don't leave any padding for it -
image
* The default settings also seem not to fill the vertical space very well (on closer inspection this looks like an off-by-one error in the positioning calculations) -
image

**Comment by ColinEberhardt** [comment]
Thanks Chris, that's a good example too. I'll sort out those defaults.

Regarding axis end-ticks, I'm considering simply making ours zero by default. This way we would still match the standard D3 API, but have different opinions about what a suitable default is. What do you think?

**Comment by chrisprice** [comment]
Don't have a strong opinion either way

**Comment by ColinEberhardt** [comment]
@ScottLogic/d3fc all done and ready for review :-)

**Comment by bjedrzejewski** [comment]
Looks great, seems that setting up the number of columns is really easy and usage is quite simple overall.

**Comment by ColinEberhardt** [comment]
Thanks Bartosz - glad you like it.

On Mon, Oct 26, 2015 at 4:27 p.m., ScottLogic/d3fc
<reply@reply.github.com>
wrote:
Looks great, seems that setting up the number of columns is really easy and
usage is quite simple overall.

—
Reply to this email directly or view it on GitHub
[https://github.com/ScottLogic/d3fc/pull/664#issuecomment-151196773] .[https://github.com/notifications/beacon/ABDBfreSs2VgnlGfIkJ016dOClkJ2oZMks5o_kvVgaJpZM4GUFPv.gif]

**Comment by ColinEberhardt** [comment]
Thanks for the feedback Chris and Bartosz, merging it in to avoid the need for yet more rebasing!

**Pull request merged**
