### PR TITLE
Random data

### PR DESCRIPTION
**Pull request by owennw**
Note: This is technically a breaking change as now setting the `filter` to `null` will throw an error. If that's a problem this can be made backwards compatible, although I think the design is cleaner as is.

### CODE REVIEW

**Comment by ColinEberhardt** [comment]
Thanks for the change - I'm happy with the majority of the changes apart from the new `skipWeekends` property. I think the non standard property implementation is an indication that something isn't quite right here:

https://github.com/ScottLogic/d3fc/pull/738/files#diff-3fcc876522bdd0aa2319befe2d0b4298R146

I think a better alternative would be to have supply a pre-defined filter, something like `fc.data.random.filter.skipWeekends` - this is very similar to the way we make point-snapping pluggable for the crosshair.

**Comment by owennw** [comment]
Is this the sort of thing you were thinking?

**Comment by ColinEberhardt** [comment]
> Is this the sort of thing you were thinking?

Much better :-)

**Comment by ColinEberhardt** [comment]
Sorry it took a little while to get back to this review. While the financial data generator looks to be functionality correct, there are a few aspects of its implementation that I am not so keen on.

The `calculateInterval` performs date manipulation using a `millisecondsPerYear` magic number - have you seen d3's [time interval functions](https://github.com/mbostock/d3/wiki/Time-Intervals), these provide a much clearer alternative to manipulating at the millisecond level.

The overall construction of the algorithm is a bit odd - first it generates an array of data, then recursively tops it up. Could the entire random data construction take place within a simple `while(length < requiredLength)` style loop? Where the filer is applied within the body of the loop?

I'm also not keen on the way that the component mutates the `startPrice` and `startVolume` properties as it is executed. However, I can see that this was not due to your change!

My general feeling is that this component is starting to look a bit messy, so needs a more thorough clean-up.

**Pull request merged**
