### PR TITLE
Added better links to documentation examples from examples on the site.

### PR DESCRIPTION
**Pull request by bjedrzejewski**
As this was reported as issue here: https://github.com/ScottLogic/d3fc/issues/539 I decided to try fixing it. This is how it looks if you accept pull request:

http://pasteboard.co/1oGhQWgY.png

### CODE REVIEW

**Comment by chrisprice** [comment]
Sorry I don't think I made myself very clear in the issue. I was thinking
that the example descriptions should be reworded to be brief walkthroughs
of how to create the example referencing the documentation examples
(components) more thoroughly. However taking inspiration from your changes
maybe we could just trail the template with something like -

> For more usage examples see the [component documentation](example.com).

**Comment by ColinEberhardt** [comment]
I'd like to have a more broad conversation about the structure of the site, create more of a long term vision ...

**Comment by bjedrzejewski** [comment]
I agree that some broad conversation would be good. I intended this pull request to be a quick fix / conversation starter.

**Comment by jdunkerley** [comment]
Think that would be a great idea. Walk throughs sound nice but good to get a better feel of how we want site to be

**Comment by bjedrzejewski** [comment]
Shall I close this one then? Not to clutter the PRs?

**Comment by chrisprice** [comment]
Yes I think we should but I'm not sure we actually came up with that  clear vision for the site, maybe we move that discussion onto slack.

**Pull request closed without merging**
