### PR TITLE
Extent no longer mutates the fields property when used

### LINKED ISSUE #813: extent - mutates the fields property when used
If fields is specified as an array of strings, after the first invocation the array will be populated with functions.

### PR DESCRIPTION
**Pull request by jdhodges**
Closes #813.

### CODE REVIEW

**Comment by chrisprice** [comment]
One more, nice one!

**Comment by chrisprice** [comment]
Just waiting on @alisd23 to fix the build... :trollface:

**Comment by ColinEberhardt** [comment]
Thanks @jdhodges - while you are fixing this, I wonder if it is worth addressing the other side-effect in the `fields` property setter:

https://github.com/jdhodges/d3fc/blob/bug/extent-mutates-fields-when-used/src/util/extent.js#L117

We've been actively moving away from this pattern. As a result, I think `fields` should always expect to be set with an array.

**Comment by jdhodges** [comment]
No problemo, I'll push the changes soon.

**Comment by jdhodges** [comment]
Looks like we don't need to make any changes to the website for this.

**Comment by ColinEberhardt** [comment]
Thanks for the update @jdhodges - although I think there are changes required for both the website and visual tests ...

screen shot 2016-03-11 at 07 22 48

Hopefully a regex find and replace can easily update all these instances :-)

**Comment by jdhodges** [comment]
> 227 results

A _slight_ oversight on my part. I have made the necessary changes :smiley:

**Comment by ColinEberhardt** [comment]
Nice work. Our CI checks for console log errors on both the website and visual tests, which should 'protect' us if this does introduce any errors.

**Pull request merged**
